{{- if and .Values.authz.policy (not .Values.authz.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diagnostic-bot.fullname" . }}-authz
  labels:
    {{- include "diagnostic-bot.labels" . | nindent 4 }}
data:
  {{ .Values.authz.key }}: |
    {{- .Values.authz.policy | nindent 4 }}
{{- end }}
